apps/wishlist/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name="my_home" ),
    url(r'^register$', views.register, name="my_register"),
    url(r'^login$', views.login, name="my_login"),
]

apps/wishlisthome/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name="my_w_home" ),
    url(r'^ create$', views.create, name="my_w_create"),
    url(r'^ update$', views.update, name="my_w_update"),
    url(r'^ add_item//(?P<id>\d+)$', views.add, name="my_w_add"),
    url(r'^ remove_item//(?P<id>\d+)$', views.remove, name="my_w_remove"),
    url(r'^ delete_item//(?P<id>\d+)$', views.delete, name="my_w_delete"),
    url(r'^ view_item//(?P<id>\d+)$', views.view, name="my_w_view"),
    # url(r'^login$', views.login, name="my_login"),
    url(r'^ logout$', views.logout, name="my_w_logout"),
]

wish_list/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include ("apps.wishlist.urls", namespace="home")),
    url(r'^wishlist/', include('apps.wishlisthome.urls', namespace="wishlist"))
]

apps/wishlist/models.py
from __future__ import unicode_literals
import re
import bcrypt
from django.db import models

# Create your models here.
class UserManager(models.Manager):
    def register(self, postdata):
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        NAME_REGEX = re.compile(r'^[a-zA-Z]+$')
        errors=[]
        if len(postdata['first_name']) < 3 or len(postdata['last_name']) < 3 or len(postdata['username']) <     3:
            errors.append('names need to be longet than 2 characters')

        if not NAME_REGEX.match(postdata['first_name']):
            errors.append('only letters')

        if not NAME_REGEX.match(postdata['last_name']):
            errors.append('only letters')

        # if len(postdata['email']) < 0:
        #     errors.append('cannot be empty')
        #
        # if not EMAIL_REGEX.match(postdata['email']):
        #     errors.append('email format')

        if postdata['password']!=postdata['confirm_password']:
            errors.append('passwords must match')


        user = self.filter(username=postdata['username'])
        if user:
            errors.append('username already in use')
        response={}
        if errors:
            response['Status']=False
            response['errors'] = errors
        else:
            password= bcrypt.hashpw(postdata['password'].encode(),bcrypt.gensalt())
            user =self.create(first_name = postdata["first_name"],last_name= ["last_name"],username = postdata['username'],password=password)
            response['Status']=True
            response['user'] = user

        return response


    def login(self, postdata):
        user = self.filter(username=postdata['username'])
        if len(user) == 0:
            message = "you need to register"
            return {"Status":False, "errors":message}
        else:
            if bcrypt.hashpw(postdata['password'].encode(),user[0].password.encode()) != user[0].password:
                message="password incorrect"
                return{"Status":False,"errors":message}
        return {"Status":True, "user":user[0]}

class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    username =models.CharField(max_length=140, default='SOME STRING')
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

apps/wishlisthome/models.py
from __future__ import unicode_literals
from ..wishlist.models  import User
from django.db import models

# Create your models here.
class ItemManager(models.Manager):
    def itemreview(self, postdata, user):
        errors=[]
        if not postdata['item']:
            errors.append('no empty entries')
        if len(postdata['item'])<3:
            errors.append('item must be longer than 3 characters')
        response = {}
        if errors:
            response['Status']= False
            response['errors']= errors
        else:
            item = self.create(item=postdata['item'],user=user)
            response['Status']= True
            response['item'] = item
            
        return response

class Item(models.Model):
    item = models.CharField(max_length=100)
    user = models.ForeignKey(User, related_name="post")
    likeditems = models.ManyToManyField(User, related_name="likeditems")
    created_at = models.DateTimeField(auto_now_add=True)
    objects = ItemManager()

apps/wishlist/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User
# Create your views here.
def index(request):
    return render(request, "wishlist/index.html")

def register (request):
    response = User.objects.register(request.POST)

    if not response['Status']:
        for error in response['errors']:
            messages.error(request, error)
            print response['errors']
            # print messages
        return redirect(reverse('home:my_home'))
    else:
        request.session['id']= response['user'].id
        return redirect( "wishlist:my_w_home")

def login(request):
    response = User.objects.login(request.POST)
    if not response['Status']:
        messages.error(request, response['errors'])
        return redirect(reverse('home:my_home'))
    else:
        # request.session['id']= response['user'].id
        request.session['id']= response['user'].id

        return redirect(reverse("wishlist:my_w_home"))

apps/wishlisthome/views.py
from django.shortcuts import render,redirect
from django.contrib import messages

from ..wishlist.models  import User
from .models import Item

# Create your views here.
def index(request):
    user = User.objects.get(id=request.session['id'])
    print Item.objects.filter(likeditems=user)
    print Item.objects.all().exclude(user=user)

    context ={
        "user": User.objects.get(id=request.session["id"]),
        "items": Item.objects.all().exclude(user=user),
        "liked": Item.objects.filter(user=user)|Item.objects.filter(likeditems=user)
    }
    return render(request, "wishlisthome/index.html", context)

def create(request):
    return render(request, "wishlisthome/create.html")

def update(request):
    user = User.objects.get(id=request.session['id'])
    response = Item.objects.itemreview(request.POST,user)
    if not response['Status']:
        for error in response['errors']:
            messages    .error(request,error)
        return redirect("wishlist:my_w_create")
    else:
        return redirect('wishlist:my_w_home')

def add(request,id):
    Item.objects.get(id=id).likeditems.add(User.objects.get(id=request.session['id']))
    return redirect('wishlist:my_w_home')

def remove(request, id):
    Item.objects.get(id=id).likeditems.remove(User.objects.get(id=request.session['id']))
    return redirect('wishlist:my_w_home')

def delete(request, id):
    Item.objects.filter(id=id).delete()
    return redirect('wishlist:my_w_home')


def view(request, id):
    context ={
        "items": Item.objects.get(id=id)
    }
    return render(request,'wishlisthome/view.html', context)

def logout(request):
    del request.session['id']
    return redirect('home:my_home')

apps/wishlist/templates/wishlist/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    {% if messages %}
      {% for message in messages %}
        {{message}}<br>
      {% endfor %}
    {% endif %}
    <h1>Register</h1>
    <div id="register">
      <form  action="{% url 'home:my_register'%}" method="post">
        {% csrf_token %}
        First name <input type="text" name="first_name" value=""><br>
        Last name  <input type="text" name="last_name" value=""><br>
        username     <input type="text" name="username" value=""><br>
        Password   <input type="text" name="password" value=""><br>
        Confirm Password <input type="text" name="confirm_password" value=""><br>
        date hired<br>
        <input type="submit" name="" value="register">
      </form>
    </div>
    <h1>Login</h1>
    <div id="login">
      <form  action="{% url 'home:my_login' %}" method="post">
        {% csrf_token %}
        username <input type="text" name="username" value=""><br>
        password <input type="text" name="password" value=""><br>
        <input type="submit" name="" value="Login">
      </form>
    </div>
  </body>
</html>

apps/wishlisthome/templates/wishlisthome/create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>create</title>
    {% load staticfiles%}
    <link rel="stylesheet" href="{% static 'wishlisthome/index.css'%}">
  </head>
  <body>
    <div id="header">
      <div id="headerL">
        <h1>Create a new wish list item</h1>
      </div>
      <div id="headerR">
        <a href="{% url 'wishlist:my_w_home'%}">home</a>
      </div>
      <div id="body">
        {% if messages %}
          {% for message in messages %}
            {{message}}<br>
          {% endfor %}
        {% endif %}
        <form  action="{% url 'wishlist:my_w_update'%}" method="post">
          {% csrf_token %}
          <div id="bodyT">
              Item/Product: <input type="text" name="item" value="">
          </div>
          <div id="button">
            <input type="submit" name="" value="add">
          </div>
          <a href="{% url 'wishlist:my_w_logout'%}">logout</a>
        </form>
      </div>
    </div>
  </body>
</html>

apps/wishlisthome/templates/wishlisthome/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>main</title>
    {% load staticfiles%}
    <link rel="stylesheet" href="{% static 'wishlisthome/index.css'%}">
  </head>
  <body>
    <div id="header">
      <h1>Hello, {{user.first_name}}!</h1>
      <a href="{% url 'wishlist:my_w_logout'%}">logout</a>
    </div>
    <div id="toptable">
      <p>your wish list:</p>
      <table>
        <tr>
          <th>Item</th>
          <th>Added by</th>
          <th>Date added</th>
          <th>Action</th>
        </tr>
        <tr>
          {% for like in liked %}
            <td><a href="{% url 'wishlist:my_w_view' id=like.id %}">{{like.item}}</a></td>
            <td>{{like.user.first_name}}</td>
            <td>{{like.created_at}}</td>
            <td> {% if like.user.id == request.session.id %}
                    <a href="{% url 'wishlist:my_w_delete' id=like.id%}">delete</a>
                  {% else %}
                    {% for item in like.likeditems.all %}
                     {% if item.id == request.session.id %}
                      <a href="{% url 'wishlist:my_w_remove' id=like.id%}">remove from wishlist</a>
                     {% endif%}
                    {% endfor%}
                 {% endif %}
            </td>
        </tr>
        {% endfor %}
      </table>
    </div>
    <div id="bottomtable">
      <p>other users wish list:</p>
      <table>
        <tr>
          <th>Item</th>
          <th>Added by</th>
          <th>Date added</th>
          <th>Action</th>
        </tr>
        <tr>
        {% for item in items %}

            <td><a href="{% url 'wishlist:my_w_view' id=item.id %}">{{item.item}}</a></td>
            <td>{{item.user.first_name}}</td>
            <td>{{item.created_at}}</td>
            <td><a href="{% url 'wishlist:my_w_add' id=item.id%}">Add to my wishlist</a></td>
        </tr>
        {% endfor%}
      </table>
    </div>
    <a href="{% url 'wishlist:my_w_create'%}">Add item</a>
  </body>
</html>

apps/wishlisthome/templates/wishlisthome/view.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>view</title>
    {% load staticfiles%}
    <link rel="stylesheet" href="{% static 'wishlisthome/index.css'%}">
  </head>
  <body>
    <div id="header">
      <div class="headerL">
        <h1>{{items.item}}</h1>
      </div>

        <a href="{% url 'wishlist:my_w_home'%}">home</a>

    </div>
    <p>Users who added this product/item under their wish list</p>
      {% for user in items.likeditems.all %}
        {{items.user.first_name}}
      {% endfor%}
    <a href="{% url 'wishlist:my_w_logout'%}">logout</a>  
  </body>
</html>